spring.application.name=logitrack

# Configuracion de la base de datos
spring.datasource.url=jdbc:postgresql://aws-1-us-west-2.pooler.supabase.com:6543/campus_c4?prepareThreshold=0
spring.datasource.username=postgres.caiasyltrhrelwjhwblf
spring.datasource.password=Campus2023CMP
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=db_logitrack

# JWT
jwt.secret=UhQKp310/t/QWmIumdC5MqA0wVBLJNsUnucE+SqjWIY=
jwt.expiration=86400000